version: '3.8'

services:
  streamer:
    container_name: torrent-streamer
    restart: unless-stopped
    
    # Use host networking - no port mapping needed
    network_mode: host
    
    build:
      context: .
      dockerfile: Dockerfile
      
    # Add environment variables
    environment:
      - NODE_ENV=production
      - PORT=6543