version: '3.8'

services:
  streamer:
    container_name: torrent-streamer
    restart: unless-stopped
    
    # Build the Docker image from the Dockerfile in the project root
    build:
      context: .
      dockerfile: Dockerfile
      
    # Map the host port to the container port
    ports:
      - "6543:6543"