version: '3.8'

services:
  streamer:
    container_name: torrent-streamer
    restart: unless-stopped
    
    # Use host networking to bypass Docker's network isolation
    network_mode: host
    
    build:
      context: .
      dockerfile: Dockerfile
      
    # When using host networking, port mapping is not needed
    # The container will use the host's port 6543 directly